### ISSUE TITLE
Default button behavior

### ISSUE THREAD

**Issue by mawil583** [mawil583/Spades-Calculator#30]
The ChakraUI buttons have a weird default behavior where they get highlight if you press and hold it. With a press-and-hold, it doesn't actually fire the onClick, which requires the user to select the same button again. And it's really sensitive to where a normal click is sometimes considered a press-and-hold. 

I imagine this solution would require Googling.

**Comment by gantgarrett** [comment]
Hey Michael, can this issue be closed?

**Comment by mawil583** [comment]
This was accomplished with #33
